#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 6e0bba5b-f5fb-44ec-a754-5af72bc4af7d
# Source File: D:\Arismendys\Documents\SAPIEN\PowerShell Studio\Projects\DESUSER\CONUSER.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
SwIAAB+LCAAAAAAABACFUkFPgzAYvS/ZfyA9mjC2BdxhXQ86MTu4mTG9mlI+pFpaUsrc/PUWyswW
NV6+r6883st7gLfA1B70cUkNJcOB5+FHrd6AGS85SlZoJfknZAsUU1ED6i5jLgzoBboaVfVk3s7S
rcytyaEU3SHvZm2nuylAVCNzMKgzslbPoGuuJJmOJjg4gf6ZdYHVklzDOE1plPp5lKd+GALz6SwK
/Yjms2nKQrsyHPTk/tU+we5YARnj4ByexJXIrJ0XnLvVPeihd9NwYZOPEUkM1aap2jDO6y+mlxRU
t3XtdGPb2kIOGiSDuJHM2HALtJJ79Q7+vVApFS+2LETcuW6b+0f9F72kUB/+A+UyVrq0ejkiJ9R+
gQtBB1zM71oc2mj+yiUVLWFNSyC3m/VTcre1GpXl4eAHYTjAwcXP8wVXHY9jSwIAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       8/7/2024 11:56 p. m.
     Generated by:       Arismendys
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2020
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
YQAAAB+LCAAAAAAABACzCUpNzi9LLap0SSxJVAAyijPz82yVjPUMlex4uRQUbPyLMtMz8xJz3DJz
Uv0Sc1PtgksSi0pKC/QKiott9DFkebls9JGNtAMAoyFkEGEAAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}


#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
S0sAAB+LCAAAAAAABABku8du5FwUpLkXUO/Q6C2BpndATwO0SSa9S5odvfeeTz/8p5ejhSQgJdbl
vXEi4hOz/redp+ORLzcfb/H/eL9Z63H4f/4n+r/g//l//v39j//xv42lLush7sS6y/W4z/+PFteD
OC79/5rW4n+D/7+X/79f+u/1/yPU6Qf2+76AMYbhDJ5j/u8Hy3D0oe/3DMU+W8yAvIWgYV7K4OFX
dZmZ6AisUHM7Uw6sc2ZBamVXRVDgnS3Jv78oyH8ziWZo4J8WHHJ9eqdGnochyTvAkNK3oZ+ECRJA
IbkuCALL+3VVk6sAr3UpIOsHgn0kBd5jIuC/vyHad+BI8A6nAZL+FsWwCEFEwXRAWSCahCA4qC59
hXyvBSCUZg1kDh0K4rdd81q5H5Q/ovbvAW2Id//9mVXviNpS29JVIl8anA9IMZuexcAPlyW5gFAU
WPmdb1cIBSD5Pof5rhR7cWC3iFdTBlFJtkrkkVW39O/vKhda2+NHmXHUA7gNFmnAOkSQJcEUaLMM
dmKlAMnl45ITD+4pqLJYlsKhDavdAXyLRZbRYVFjko7fO41GwC2m1YSpfTHSL78CxJRKIJuQI2OC
tWeQC5nH9hD5C5guk/AFV2O526A8dTVvVHQFfuuQHhuFmMe/P50SnkJKMTRlx+zgyEhNbtdtCuzR
aFimq6INzXRr80k+g0MsISp4nHgnxovGbSXc6jCeTtPmvpn5UP/+MMnku0CvOOo6PzTiSn4Vp1+b
/z5AwfZ738r606VUt34SU/LU21Ruo3Auh3YDSMRGdOkLdY+DfmFz5F0bwhUSTGSraOhGqCmScstL
WqPOKVl3ELL7gaXT3V1KpMYMW1LiEtgfaPeZIXUa42HfhVqcH107VE///vp4mPQCpQTDVZtISxW7
0PAhvLhHc7W+tZdV2dqddtRucJpk/SZDkhskXUUQYHlN5ibwOefss8YD+u4bMSU9fqbpTxhFP6k6
qCsGdog/Fk6APDzIq2pCR2EeSKEn8YOB4FIgoB7/329dBNyshCADuntI/z3Ti4IgvB4uWDvDpouz
LVh/7rWriTl39lZ6Hd7j2U3emgwjhPvRoMvLalxrz44Nvpld98kWwTCuE6wW/PtLHpO4dh99twGx
J6WQoGcVGYFxlENYWCkQbnjNBziZTGyWh6rj4Y+nMOTitF8YKpZTDbPgKFf9Exfuf2vrFwI8qj0L
vk66yeemASZuEzmxoYkjYM3XXXzkehrBD3mMnKUpITWd9ufxMeTL8igKNU32o5xV8s5CbWLvvmhO
zd0Joo10JBafHxjcFGG0O3yPuvjzv3nw21LPXzrUXivdEHrBCoO4xFTfYN9hHlIeFmVye+fU3e4O
jFkUp+5CGM3wIAGszKQ5UGnq1FoLU9U7FPJqWvL8oLlPyYR5jk+3t3zQY6jkfVlCdQxoFDH+/Ym4
+mu+oxhqgdmt2Ccoh8/uEkOtEfekP+xjLINdF42GiaI9IIUQoZIr6xLhXqDRCFKni8jQAs5Rp/K/
vz1rG5SYK5MpZARCTaXaDPI6JCJ7Ll7+8grRFxLy1OJ0RAYpo9VO2COj1RGtw6s++/FSfPy9FobB
Uv/9ycHPek4g9v2BWH8SSzt+apHzqfbg04YO6w0J6sgtYJ7klo3VvMHLGbJTTOIE/cVoe0k9nfMT
QWg48t8f0K1ALuRTHwaK9ZjcjnDmz/BacIB1EpVGajvhHjJBZjRrCtAujQqEaCod2Ef9kJ0VrxzU
jkwnfmqff3/ZJHV4LDRBXnih7ZK+IUSuc3VRJVvg9z4NqQyuoMQlzurFrQHekzH1kZ6Yav3swwaR
qR9T4gUs3tW8d0pORBEOVfwOZ9KOpTwJNGqBLuvXg0LBhcAMeuvAN5QaTTMcKeFgFgrFBF0l3TXj
5sBlO7NJuO2q0b+/m4et+GutD1GznvTFIloqzdKohB33cgiG2PVjTfvgF6oUxvnuCa8vQZf4SWAY
ThTU0wavDOi7C3W1f71XuL5+6DdFmvDprvnb8z0TYsBBkzhNYaQ5svR1p8LHj3qBTGPyNIINP+ym
2W8KAezvDlVmOPbks9f1vz/SngauFlKT3H+IOl8urtjUUTMBrrLy4mKkaV+KELXgdo8IPRghe93L
gdT1Z00WGwUAX1TirB09kkv//T3XIv5KdlANQ/CZWs/vBhHZ+md/3YSOfnZ59mqfrhPNQPVJxlHm
hX2dmdEEZ5i/TcCcWBZeflV206t/f2NW2r+Iq7hz4vjEXaXBgxUbcSJIM3fjyn3ZnOx5674VfZAw
wsaFxUpX7+QMPaw+aXYOQ8upTRe7bf/7E5ajtqiTaxO5pYBYBlQVq9g9wLPZEIJPWM5Rdc+YjhZ7
y/mc1hURYI+PIHfxnMa2XJ/IpV0fN/IZ8Z16UemU7zJ8rdsuf1Bg5tTaqIBIftxaMfdRqDtfq12J
Fwyfpz6WXtdLq+/rAD6dq/OeoQ0/WJrbOCG+//5+R0NBYkBFv2OZRk1FdjGrv/n8me7XNLwAx4fs
YHYATmxQObvCHQdsra9IfZB3qqx+u8KANcQvqHBvypwuxB5HgEPxyOW4fR8aB/uH6Ht6pFeI7PEh
XXdW76sdeGDcJaz1jE6QWLYVS2fVt8Y3tcrtcwzUInw9BMnD4eCRMEXjtAYAHs8UkrWZ+mvf/a+1
TQT5Gs2HOJYKKIKahNK7BrJYSyvtux8TlfsCkF+5gRXeu2+eAdy91v9UfXfA4sZY8LnRVeZKttJ8
tKxVtLIiBlzj3JNP+NRu9G0PeD3SMgI4ZAYMHCeN0q+tXeP694eGcquyCxgpyvjwbAAcOs+vCNp9
cfhOBvzHQ68lIyg2sEArCupN7RqW0iXxdDk62TjuKsdH6NCPzOXv1Hf3qnxrU3H8ZB0qFaLOtkAx
jXYtvRlEtPwKiuZPeyJTsB1YQMMg2m9VVHLxsGyOtkA7BXGJuQ36lf/+PuLntHvw2N3YDscMSPnx
u7cSD6WnqNNi1D7D52ZNFpJQOgmG9aqoS/ptVkuiZ8dEyxIgjoKB8mBer3pxiGkILXefGpn5HT++
Qzl0VNV6gXE8c4YaGpuqw6+71mn2LgeioPn+JgWULgAt3qi83vvE4QYvAJb1qjd1F9nWP5iP5aYd
fSc0dkltT8Jd2bAHlS1YZse8TQexAfM47mrF+8+XEo6yg2n6sMWyj1UPoNn3+e8UpkaLvZt3rkuC
bE9HeWJ7K2VWKLhJIv3pUrVdLdJ3lGhjqJOLHmNfQ7SrksaN5Z8oFzfnF9AlZW76q7eKN8GjQ9Q9
n2Kft0l/S26uHyj6/ApXjtDuJrlvhVn1Y2v5sZ8hT/o9q7OdyCtL8ok/LJ2EtCSWh/DvT5HZK3XH
q3Qdmae7hi/ofB/beEN/tMTKvy/huR5LIfyPDUVgWYgL8mvZRsV66YV8d9UaI4vkx3b8SPz7A1mn
9BklKpnG9gdM+4EXwiG/E16dpJ0wcZnlbF1gIa85DGd+taOmayad5O+euwC0t7Uq53UtTmQJtH9/
2yYlmMckehHf2OmgXxD4dtt03Ui1DYk0piE2SWI72GeZfz6Rwb8usetktsjhKn08gc8i3OWSaHex
9p36WlEs44qeYWP3arvKa34dpvs0m1iRr1GqBkpUvSbTYs2qqtED9ZOdvxH80obVyVm1g/1VnBlK
drz35oIJ2ez9kVJqk6fMVtFbr4t1jwlRe4NV/8I86H3P7ZnRM0vawoNYEqY5GRPRr/p77EaE6uCe
fYMetvjtveLucbNfV4LGv4xHh173XlTPv76VMt5T6xwKX4+RESmkXq1qSCGgZl9r9PuQ95kP/iN1
eei/ZSI5b2axny9Oe/rhQk1qshRkhaDd2Lg95t/oQtUAXJOUfDN1eJbn4xYAnseduS2m4/Sn8aJU
MVuzk9M+Aan8O1nzNBpBAT99m34DxtttVCdznneMfrMMxEsrv8eiR6TLfQmOxQ21cEl6EvVdCF5v
AXiTo+rAWmTZ2//3BwOuBmzVqOWgSzl++dz5ZwJCr9+r7PEXQ4+oHZGiOuYrZDvvgVCCOz6b89sc
oxt9kffceO5jwXzgvN2yQlVN9WobtmZK6tAsTPugwpVIvHA2wT+6ZXw/fIdbtLGUnnY0CTMtD444
yRBwzuMDEKZ/ETaUVhR72+AcQsjU/up605u6MILIxqk8qEusG3WEYSuMc8zdRPxbeGNF+GJSLteK
SFL0WhcpSxyQyfVfFMBY73wz6909ZJMgYZbQ5xEDaE58BPlIyY9vXkqpFPd239pgRMIpqFHz6ZiF
2t/Zha0xMpez0ynzE9KisGrf6L3TXH4wIBbjcnwBjVoHxlmSWiuMDwtbn0SNy8GYQcVEPkMjbPMe
iTxLMDI7V4Z/1lN+IFG7nNUjZ95/ZFRePHEDqdS/s4CsdWTAvF7zj4HyUtOJGVPmaX/1VaAImWBr
5KGxGjmIOPM6+HmnRWl4gp+PUKxQwpunAV7m+3QingEBj6G2dNj40eAuPGH90Kr7FbYqBuIvkkTq
9kaAKwMkIZZh0sh5UtGlWZkgmBbdIKzgTUBtwiWl6w4i9aK5BGLKq+ejtFmYjEOz9+kccX7iE9ST
Noyl/lksvJd16+1ylGvBVO5+KFFAhIMUm+d18v+w+JsDUiswRu6RPDeVkuhH3h7oW3zoImUhOX4H
v0yL+pGPJdnIf8vdIy4HwfY6C8dz1hF8LHTbjK/3uvlsehpAjUfGYXuc8R8NnaqIh1tJt+EhYslY
PDo9Vzchje7dxnOVVoJFIUQEBQxfJTTg9fhIxMmXARUyXJld/uDgYMHFYx2++tZv0krO7pvMXH9e
JhdUwNNBcj/F+bCjcLIQAuF8B7Ul7/c+tODCkx5I8XffwuG1/Z1OPXnc4LyAexUkD37sYBzCFz1H
CjfxIfvDp+LzggcFsVSH42s2d4oho+0JnRPwSR18R0fkvdNmaH/YU+VV9NZapq2hfkuJV8OG1MuX
e3nSSU+egyQ7OQ5Zuu1J88vMQjLw5d7HyaG/kQDErn6fkfPOArSgIQn3wT14L9BotLLBjSN8qLYL
qWClbeaDJKflGYKXKw+OaY26i2d5SD5CtgmnSg+UFXweBpT/fZ18wpufanAH+8uRoK9flNvJZV0s
CvpGvstZynVw/gBKPpMF7TWxSv3dYnh8tiobqmGMvimt1Y1S8JH7OrlRK5M0KpYdqXospj1Db54R
rfOxcpU5u1JFbcMZkbDQ5qvWeAKxfCdpvrHaTepfjS3oLK3KhaHXlkP//tQ2GEz0xQDmXFp2zajE
oy/SPBuDXFU+YgxbTQ2HhEX1y3IurHste1mN2wzh0+cfiJ0CYhQlGbtKz3kZkFfbkywkDneghpDP
R/rpA3bFu2A4Gmyi9P7Ar39akfcBzYemGv9cQZyEXKKcou7GjhgCYhJtw11++XStUE+pYhetP9KJ
1sYr3c2l7c78ebAK7rHB5MO5csX1EL5rCFY0UQX6E3ZSMlwAEwZpBeGfyElLYbxuGTkJjYBb7ST6
Gd+vlqenGnxSzldJbZUIBwUlZ4nPbJzSr+qCSBH31dSas/aOX1O7+Uf/3VffsY5Cvx2p/okf/3D5
KUi8CdjIOVpSWj99CdxJdpaibtpOU3smcQR4+czY6otv7rAmhmknTu1QuNlKzk1MH8CAX0caf1yQ
PzBd+9/6N5wCo9y8+8VFiEqI+1NwJNxdm6nqLPv63emQxTjDOwYsQXBYA0wMq3zv6hPu52C8s0C3
qOlEfvP22OttCg0Tt8TCf8ym0tXmSXt8CoZXXM3IpQuC0zKofNbskp5si3+QRrC8Vzp0ibHXfymj
JtARkaJZZCH1wyi1FpIj9QmH8KpoGUnC+2HJXGFbw5hKGr8ERXs+fa0JmuxP0XuGtSWXcNgJ0ROf
f39+4LaoM33tTHNH8gr1LaxtJpkJTOcEA+6WW/wt++pM2Cw39c1VnYqgDLacZWY2O35LLC32HTMb
4nz913vvRX179+M69vawayRKKoJHPg5kk+n78ydEzA9ZTKYo6eRNmjWbckzDfoVZbHuIVBSj8Rwi
lFWaf/vbcL1kgB1XODsf5ATr3Go4MuJgbegjHFFHf3lcRP6kn+etCRNRxYrvpQieOr/x6mA2lXTs
TnJpWlsb+Pd3JW1s7wA99vB1PiYuWssPdz4Z7f4G+uPfrcFotoHT2+2xXarqiR8b3vLy5SX2x2QJ
xVp0yqnD54Tg72RlWJcJPAw44v6Dzlff4m3LAhg0W+RpIW55g3OwJ9xpAo3UtHpdbG81cVMThIOg
zWZ6IvHgUbDcP/PV281xutj+0JgiHtG4LWHiceW3Fo0Rnd9fpG6X22tOIMYSdRqKDsM1+wreDbSv
aqLNV8bdDQeJKBGltyN5czjjKSgRkCPA4KjFV8jGph8iqeuSiAePPwfJJhL7ZO0DvhwsbQBs1EUc
t7QiNbqU+Oyh4IZ72to79ePYHnhqIgW/DCQTqGbutvPMbOV9qXfm+vAyf1RJcvP13OJggks4euOI
283d9+Zq//WzQG3WWWnGf39dGdDhg33ADeTxzzMc81snTjkHfyHwEOSWqKjhqNv3zkyZu4OoGntA
X+EwrLRsP4hflCvGKFK1aiizmP37ezY1OvjPk1Q0AR+C0VwHg0qH3nxf53npZ18ISlcJzChIdRcA
X8a1R4ZdbgRfzQA/TXsvZqPmS9zby4Dd0Fjw3U0Dvk5uP8nqod88TbKZL1lKqGJbx+I/qcepF1E+
aP/lYXLuXGcFhPjNr1qtMDFnhyClXrT/98f/8i36JT3tq/6MW/llJr3IUBzWLdJNOZNhkLb/wBvv
H6Tg8i8H+RkXsa7XF5CZd6IopokOCBVhIeJ/V8OlQIEXNY+4nMNz2la2mvp8HfvIJYpoZnORxEBp
q2dNkMIcHXyq7FhiXL3YOO6ntPxkwf6cDrn8qne9oAGLiIhE+zkNfXAuxol49Vgoy1ZGzmefVVUj
lJZgpJ5IhKgFMlWKgP6pY3v4YkWrLJoIJSvSq8rrIYTMB225ogq+U9kCtZ8Jyb0Xe53HIlAnCwGd
UetlmPFV12NmDgH0nfekur4a5r4WHhY1sn0rWP9i7Eu773wU6hzisQ4o0xrY6mTEWMqGGzwNGPhd
nLlMeh1mMnluMvawo9Db52+vNBQ5Or/z6tsMGJiO+wQvfQgwVC6j59vNHS5+n8scr68+P6O+3K3p
oJO+PmPHTZHSaLerBFCYka6Jt+m1hXuQqrabQ0hK9HwP5m2D9wzqVy/D/iOIMhZOkgfx9QS3kWmF
l6cT5riq1O8ryA2hZjPvj5TIgkNMKE6YKHjfofuzovLiC53wtug9MF8YklYhjUEWnT7p5ryWWqN3
Bn2cwnb37vckx68HEGxxyTkeHqRmMJYuWstJJ/id12AMEYDiVeJ+OUs1cmpCBg30aITujQWIkLRR
Z2G+Pyg6yoMfCgzqk9op4UqptmpZOTISOfxttEog0cwhqdzVTgulMu9kufeVHcz9WJbg+MB6XC9k
uM2dTZoBJC8MwB00jJ2fjuK5OW5irvOPoIKkW15f+LLJFx5fu/7eZ8j950g/Mk6vOsLysCMe37zj
R20UYyLoIm5fi1fGkBVod9CsLaP8z9MvlX250kKV6+mmBHDCyxE5vxzHDOyltlVw88UVM4oiIdBb
rwR7xpGqHaeKLElQzIjMhXjqd8bsrswA3mLBZb7MKiyGYybSoxznpET+dTP6XRvGkwu4or00JF8k
U5Im/Tkz6WB7kpVFMvNzMksjmpZxoxVQIg6C9Mu26T/m3WozZX2nyrRP9Exd/H2vhoe/YZAj3f8e
ZtD2FrhvkLWZ1BZ1c5edjyKO4ttk9uPn6NBVEc/QwERWwJ+dU436YDff2di9v0jLf/79Fe0v+1Hh
Q3/s1UFF0Si1gQmpSax2lWZD4Kt9kG2eVcI03VoDETxELEUFsDVSFc46lvK5AvTo6GxK37VVwMRv
a2Ln7JLRI7PG8CU3n0aaHdXky/SHd/vsfd3X1tyGR95IhVOoaD6uxTlenWD1jqMfAdUm9+Fe9bI5
tRoRVeyygO7SRc2SIDqxo4Ydnvd9SvO3LMol3+waCWs9GLNV8witbj8Jpo3Jfgu0jbwAVH7LRv/3
ZwtENUWpigv1jbxiGVpZkJHnQnLNKTDFwX/dPGHsFCIZ7qGZUyExYRmCgZ2miqIZ29yfw2rCp3TM
10PSTH1AOwirIGf9DAwTep8S5N21TCOpmx3kCpveEasR8OkSONluiMy/14/4wijdVvJHdfzDJubX
vLx36nF2fsz8DFwntuT7N5BuvPUlhiTqVixhmfcF9zPGqlsr6DdwuPfBeZ6XeUrsc4fgMqoROEU/
irap29fJm+difwyXZdCT54pSSHTtQl/LNdiPGP5yP5X2b6P3xesvFeUg2JrmX0MtVT3DIZ2CIl7T
sibtjYyppJcBRYC+yvKId8k+4ZNHQy+dA0HbdritiAZGOuI9gnva6haDMbLluXyAy89zgqY0PiFB
+hz6MawG3z7D65bxF7rL/mDDi0w84f7v75xIn8+rjYsB9WO8i278GUHP+sj9QU7Y8nwYkRgR+Udg
312YY/CBEr+P56D498d4WU88n1KI5+mRiTG3w4dIcyKkqrFrtOSKup6OLpvq6tItP3B2jDqFTYN5
5VHucLd9fdKHgXGkBN/MGnZ2kmLRs5M4sgPZda8a/gZF42gC/GTq927Bb+VeeDDJdX+YvVr1XYNX
/S6T9uZmtV3G88c0fPou3X9/nKtlWXEo1fE8WxqZztpsEN/jtMRBaMcOlu351Fd2Wf7pvd8qxJ90
lYLAs2cKCJk0Fs5MX2n4YssKfBnwsLTUeK/zubiuFcmNKuz6/JpBTvi/DVoBUG/2V02V4T3O28Xd
BDulBhENg6hKzEu+0RV43EkPlMH9+yMPKwKg8/6BvNCl+/11DAhY6xKmNFh6C6V4yHFURbSSDx29
1jTSIYdhqPIt8Q6ecJQqDPOtL74oEi/tsk2mOjeOfIxuPr16NeyXZUsczztoHUXPgq8WYk/uPt0q
ejFMUoGg8kwjqV0GOnfOFRplfkp4KJMv9bboai0ELyigi1Vp0XLdzfbwFmFW43QyDLXbgWxyIFdc
hPtZXq7v3LzE3IpG2hr4O+r9PhH82CLVwuXbkb4/wKXwo9szH2yrfXi+viok+JMpomy6425I5o+h
vy7KhweTO7Tv1edTDm7SAkk1cr+1E6LFb+qp++/dJhvlEYdP86R4jBmPF/p0poQmT5g5Q54l8CkQ
ow7OCeM13nqnQY+RSzmCpZNf0fu+c/g3aINARJ+uerulEaCMBGMT0EVzA6BnR2BxfHOfxzeumjrU
4FRie4GRnxA3WXXN/I9sBELu8o8iZEMTk7rzPX0j5JfgVUg+5vBmOZhzCXdpl+OMFnus51cEh70L
0QKy8NyH5l0Mbwof1eq+/6wLXvCsNMgY3YWhR+uqNIioHcyvQoziTnc1fiqb+noAgT0AGm/59Asw
4ZfLlCmYga4mPPg1O9wq8aAKUdLlybjzlEf2Qj957N/BDqgZv3xq4DO9O3xs87d7B5PYUCYdzuvY
MtcVWlxGmDBGnBD5Um2gP48RyKX84D58H0IZePd/D6Qtsi29SbvezHINg2H0y8ay+Tcmles9GVx1
Mlq0cn2gEqXdGRaZG4Z/LMEIuRDAAKP1APUL00sc7JFCx/SYgYSY6G9/+wCaFP/syMYTo1cbjxnS
yt26D2NffJqMqbB+ulhy++S0B3ZSO43tHr9pgXwzvudTeK0IIOLzZQp1fyfLU8eW4G92dpowRhEM
oACSisjiHJ0qMR/Nf4qye7pIGW3AOEI2tVGY+Qr0QJjW3i104HYVIW0qCXPEewoo9Xj1x6x/Wuip
cGf25/UN4epsbUpK6V9PE8hIOrG8DslHM8pi9lv5QaFt+IH0f2+4ivy+x77X03+mf3/Z/sAUoGES
6fra8IVbKFQ3794YstAV8QJ6703FIGkWji3kX8aEs205klUmvFd9ydGrb8ZGg0KgLv2//rbETOBS
IN+m5JSPtDnNS3tOPydsbocGsQ/CNRZiUWLM8sPvN0YwECaAnqgewuaGjP5a3OvrJ8vw/fsmYClH
VSJv3ifffsPUNBKeX2fu2lg9vlieuk9xEgfDZ5t8DiWUA6X5da/8+nl4ZKLGucogh7lBS1A/8m3R
kHHfQrM2hfcKiQmiHqwjA0/L7fSf5kNqXTyLZ4XJ1zjl2rRZiFaZC3LR2HHi+5xKBKaEFSeYCav9
+5t83cJwiSWDaeq6mN5xqjDN8eW+MbRvBR6st+j0Jm32MSbXxK4jkPu5sDRktOxL99/kO1kYQ1s5
IeQvA3oiKmZ6G80FWVeRYURYz21Tv1o5OMq2dnin4MfsSLv1ZDeI+gOQNZRgCAnO2TYOF5F+QHlZ
YV7j7yz83IYAMvtz2EHPS7CDphzpZClvmwpSlLU0HMXvZz0hpTo7wU0ngr92BLXAYImvqCoWix1t
3h4v+FXxv79QnoaOQm09rFymNThSdL4ieMyNUHJJsMf8E7Ztxp7TMnHt7kT6vSJH4mhyG9xx30KY
Orx4o+C+kb4JKO9mvoYxK++hSWDcxsZ0J825QiXbgT2HIHzDp74KZfsx+lAE230oGj/+ZOSS6tLh
AsxXqGBiWCmxXnaGu1j8wBW7o4Oo99RZTXp7czCb2A00TsvRhV7YzvJOROpQCeIGemNr5jvejMH0
/BxqXJQ8luYJ7qv+XVuzdjqd0TNSszITKHIZf2D9xTKs2JO5zUJvjRja203LZ34t+Hydfev0spdL
kaWglxBneG3dJvxkQ/jvD5pR2VM+P45YgVudpoRvx6o4yklZujq0JDwTXBFX9ioZgVUmzODzkq/z
+QGFbu1BccF69DAAK3z02P3viUDAGhIsQkg2z6ARm7/MHnKaQtKfGQkyHrv29IZk25fX7RvrD/rZ
Z/e1qSAep3DgZly9MFRS4pIMq39/vQaRaMEsdea30UUJMK2z901LgbcEHGgwGnHZKiOswErK50aC
wAKUJJiSiDf1eOg8YfIRktRKMgJ5ExCmDzYxPcogkK+Rpy/2M5/yDWRIGDJhf7j7MAAD44iIsDwg
2jSae6AekHvHAj84YPi7Ylqu+LtTmqj//VGCq0d81+F452vM4PQQ59L66qIpQeW75nUuSw60mkwu
1nlz2EDR76EvWGip331Da7B9TZzS0FAwevnfH11e+q/Cgp5M9bbK6xrre1rWav4Q7NET6STRwg5k
v+NsJ3hcTC+0fLb1gdj1Xd186RDhCXUuNBarvy06zzn8Q/yU0QdFZGkUmHS0gPZD+6vzopOyknok
YSI/8RqkRysIviNqw8dcPvhC3nsmVUWBOo8a8uTnVS/Z5eS3eh0MJpbnA8lZOoJdM/XzCNLJdT2n
e4Xtr6TJOckBVnt4QtFFkFCOCk9EU6JvHipTvIwrX0z//fHSTwMzriE4+Do0BTvEiy9sjDB3ysdq
OGbRMzyEfUGXV6LJW+qBB189plMj5WcRLeipmqDbB9v/cPO/Z5RJcQ0eUMXItBI7xrigd+Oj8F3X
09ya+dd8dkS0I33mwwwY4W6wpND5fg72fvk5+vVp0xu6L4ute//7cyRuJiWL3plOt7fxUu3dN6yH
8OzCOwfcqVUl7t11fV0pWGeIK4YxQxUkdPpbQXS+w7sANZpZV5799V7zAdcyVw9p09TCsiaAG48M
Sq4TtysclqtarPWUJBEJS+c00Zy0HbcuIzWgGEsN7Gud7mDBEVdGpul/fy+29yUtkLeYej+nnBtV
EgbisUJK+1VzBDmGsqgcPKotQKXsbTt1sEG5mcPQ4Su56C56Hix+Iip+eL25wINva50/H/m74UB2
tiH5Qq6wiHd/3EhL6Ngmxf0PgaI28Sbovb8Vq9fpvjNi/YZdPj4DidQOTaram1lCGYspL4s8l+S0
010ji/KRE231KI9jDBjPwWElsXwUS0d4+b4mP9TlyrBRKx6DG2oVbx93iMwsen4na7+fVFd5f48s
2IjOSSaCuKWihpqDD9h7L5wHJdeupfvWNHYH8KMmRGg7sUdGs4tOybhQZpwm350BgdctN4vIobCb
qHiaUbCoNMoknxYl2wnHQMjL+zyhCLwcU3nXL0yEq0FD2J4V300guiscRAC+qy9OfIRXb7XQYUF6
8vIx9sFqns7j8KUukB/z97maUNVocNoXfhXdNJWxqGn3rvolIyz2Us0s4Df8BIppEjGU1uO/v0DD
Y8c7nM0ON1vXT3mXmlemSYY32Nvqh6YNvl738WxP8bPrKya36qxaDGZE7o+W8wT2POoHPep3/uqt
NQEejQmQNBIKNGsQMVCifvxCAqlgh2FwtRK/Kv7vz/jm6z7xf++piDXz+2Nk4ORStEYU6kvXoPdO
vdaidFZ7+PzxWsIFASl4a4wJ0yiYFyhT78BnffgGBGF7JnKmcU3gMbpfl/JwjFwuCIqx8T3AW8Dy
svivvymvwpsGwss2tTPJBMEfuSYY/xwbANqmaxfi4PornpCm+TvqW1vmHzhIQ+yfc0FfDbgDSQFj
nYw5b8qAm13qABZtYKYuALBMVTGAXHyggIjbBnI8Ce/Q9G6C+F24VLniL3Ud59EQVLUpVEZRxQNf
BkBv7aveAICOnSQzKkcrE42oD4CCxFZJAKgwh0Sn0dGwxdPyJAv2aJV4qDsBybWDQQkiPECqhdEV
sb6CUge+CsFFFxw+b8o+uFgDZwpaDv6FPYObrpWROr5gdPwrlnrQ0hiYWZin/6jPjZJwPoGVj4Ap
3ORG9OWEZf+8k/WUJswaVm3ITKgBLeNGn+0UF0rkWOZ2vxDTpVe/cvGSZUwQEygwH7E2oA0C2tRR
2BR4vLkoIQQ+SP/+wFUEn2I0p4G8W+JGmDis1Q8/XfjJzHLt6yeCgJ3MVw2BMEb9DBjDYxhYkGdp
jFY1hy3P/kibMotw+ffnH9i7qyGyGejxHBffIwWy0MihH+CDgTqfiyCMMPwNiAlTCMFeKgkht1Ko
Uz1/27RuffQsdFj5ix2vQpZG+8GOLXcN5XrqPIgTW0CFjp15RxfHQ/cuveqgnAhcsNN7UoDmuTUn
WMi7e2X3am9vKWHMMT6u/55iL8N7bzzCMall/E5GaYyWmX1ICfmt6VU8I0kU5pQyXFrFKfXDUXKu
NBq9BAL9YCTtm7OVAJdWKEvWywsfbf2BUrEB1xKOXwVKtuIpSHPiUGR/F0IlcNFPb3VCSLiqaim4
x6WsTYNkaANuS45+KzKrfSi0Qsm3h/TGmnjmmt1iCetdTSwMt6Z7O8SKVlvTvrHZuFrfo+J0rm+N
lV1PFftFyMj5pwIdqFNVU2+SZnHa4zsLtGw+aZ2c80VlRip7o+NA0kwKt5Wd3+g0Ol2dXghagqsj
H/Cuv/3G/Cauqsrudm6MVb74yKblg0HI20M6Oqnp52glZy8zvT7U22dQnVUF3vwMM2NV55dAhzbS
jFf2YjWxypSe8itSS+zGfT40EkDeDvWRT+m9Wm9qA77l1At4QK+xWyKJsngJvGYSlnW7Y8AuRFII
l+TyftEm41dqpCz7lTsFuBLykJ/PQ77OZM7UWf77KyikLudDzy4Dc3t6DKEULqX+SRD9wGkwIRDi
2dEA+z0u9a3i1FlGvVRhLsjG9uRXwVB4eLESGRa1l9pyXSf4uLriUnQO5ENOXhLCzRE+3REmCxmn
RbFkvgMWyIYW5hqPcQGzH97uLE97PzFrkJgJCMMMw50v1zOqIDhyy+ia1svXLrzx6gUhuD3M8Ogd
g5rOXWZg3QNAJ15zCSY+S73ey7bN8zChoKQWM/+uiWn17d+fEnLVw9wMwKCJq1ERo7MzX3KIw7CM
euB5mE4ZeXXMzOYUBqOs1DvLUbJ361DflY87dkyZG+GgVcf310POhpk7qwMF1RFIN6pug8tHN7QG
Gth0LYculNE9gxGC0mg3+mOhnsHn3FGXMgJnIzM2tMeZFYyWovK2mvZk/N97S+uelAB58pcJfdDq
mEvJrfeUtTaggg9hYEMeTlLxewhoOGJTtRM3xtvM3p56b5zUN9dI699fOX8/GXUCr3tRkXkrOjnO
x3wZJe8ABShA255ljRl+Z3Y6gA8EwaIsvDmmqEt5Q9cKjAlyMFzccr7G/sf1zilHbpZa3MtsM5Yl
p/xuyVW68aGULJZch7WcqZxE2Wfw+ML61E3EKEaoDhbe2MWAcOxaxvtinb9/f4BqN/FCkCLm2TfF
KgzOhHgHnb+NohfvAvhZE+VSq/d9FwCl48EzjECecbF0mh7ayKcrp6pMtBD+ftOZHWXREZNMaFiE
Ga8xbjq+h6cRA+NPmop5BFTBEWaPrxMIZ8JEQPA8NAO/MiBBkGPj7LTkiWo/BgN7//4YifNHhOst
0GLhkWRThRGjKrir7cPKKtd5r0x40xCzpywRAZJwprJrs/NFEpeYO5YY3sH8Uf/unvP6mx04GNB3
XYKx1PD0zMGuC+PpaClo03bm0CeBeE7BpM/DB8OY2Ezl2+HI7VjAMm2DQjVICO2X8n4l/M7C2JaV
swIwY82QCGZahQ+0yKQ8KoWaOVcBIQ0A+5U4UI+BxjzA7/2yuKh6gMIxCx2Aieuuuk2yK2a8Z4p9
wIML2Ok1Vt00vS9u+hl7O90QS7pqPfox7DL0oaHvA1QWzIaJUlzMoVuKfYRTzdRZq4khTiKjSL8J
KHTJSYMMdJqcoYZlhkVj+VbzSFhnSvObZwpzmIOiQ2a+XuYz3eoAZ7vdAZqPuVimbUEIX6H3a0Df
3v6WfwJMoL4PaalE2xoC/U5/3vo+p9YOuqeSK8+UWTUW9KRfu82aE2/2p2E5xU5ikyMtfCaO8LsD
VswS//6kU+Y3TXfZr1Ofyb1NJVOmt9mVLC4K4KxfHHauhJYpZ9O7liTsggw5XRiPm8RY9oYz6BIH
viR7WvOSeJUSzrmBfl1kYlX4P0RK0QLFIWqYWUbjv4xa4XwDbf3DcYYN9sEvLJiWzXXLK4vBQy0T
BkxGhAOfeUn8eeMUCn7B6Xa2ajqPeRbfY8nXE/IwB3UEz3jeDhI5n/Ja5dF/ON36IhPfafLeSg3G
okwSHi2nmRPxZhbXxwDfQ/kdf3gaTxNAS4qjzXgLZ06KSHnOztfl050nA5zVDXKumd0+/z0fyC4z
qUbRPHpxpZkXTXonS0UYoUOQiKG/5khCu6FAZBkrJKkaHA8pK1PMF8lx80bA2vlh8jTkmSk0HqIR
mOjAqeoJd03FxybV3lkI2i8UqkLWPRRIvZbB5ExSyF/o89+DCUJ5zXONp96SjoD/hXoSranH/2Tr
PKkw6M2uSloNzE9Vm9ftedMZNAcb9gSB3ywxmz200i3dqHbs1PZD9PFVh+uc3AU/z1HL+m6oJL2w
FjN73disiCc29Jb53NwjqppfljG+W2ClMhkozND8KldaF1wyNHOBmOsHNdjzkrS59aYBWwDj/HJo
QkmTRweNQ6T47QwZmYtk0wqMMLzqNUJ296gO4PenjG8o7QFr+oVUxCc5R22VT++4YIAsAIOvUmeb
gzg/1DLQ1sEl9ozSMKyfZNk8lsHvKYRKPCuY8zpYyJIb2oZm+HxkEM+iqtTCOJ6iz+dEqAgXDx/R
0Rj0jcMvknerSMPVwRkvAAgsBrY4Uv5NGYYgT+vBro2oXJcRWn7OBJ1BmKgcwVNNfu/cOu9JeJrO
kAyP2Gwn9+NmUgJ0vF2Th5xZ/ZIxPGnXe6bLasNcxvYgtj1WFSvS/Vlj04QberdoLEwjmU+ERJ6y
BEcw8SCBCwXYbv5+OQaU//vvtFandYhTh5L/9hBBq/j20w0EC68Y+v500V9KS2EFSNA20kAf5MGy
rtqIH9k/84ZZCmrCmAt94w/jjgSOIhv4NlpD+qHRvz/KYJclbjS3TtrAm0+0GAdLRTIYz+a7FIDg
w+fuNspve5S0876RBdphfiepLiTAZ+RH6POBQu7RJOKl3dbgg9hseIzKIQoctl5ldk2o6pPKmP6q
6RuNc9J4XzVy+jelSSmb1JIPSPxlq8cHbvb75N6B0I/7e9N5pPgxF5Rsi2RLEqWPJY/pg9JidQB2
ktCPoaDCWWcry5h8BhulM4wkc7iJeokKyQpxgR3WgYFhQG+v3hyBUMTrqiZHeuuAx3vf0C6Q3AKx
7PhBOAAU3ZtR65OO1QeNyEjn1e6dD/b5wshUqM1/bzmYR5pmNe0loyVIaxA6IVAnr+YxxFqq1TPC
YI8HIeM+xkirHtANQpiMOJA8EJxKQXQRmxNK2LZLfw8AzlRZFNyBvneq9NVBgrFYcxyr23zMy2dc
eVSL+I5JGEWBHAfIFXTxgP9h4yob5OXALoqL5atkukbQp1/nuZ7IHH4zK5JZIvwVFYW+2HB+4bzY
O3HSM4h2S55eZxh9fcVvVUmnFkNXjzVgIPAMDnag2cu4JcH8FFsvgr2SvVlPBxV9ZCYF1mQoy6SF
UZbdDke7S2B2hvJAt4fM0w1SoCx1/JIMTgvgUF4IpZk8N5IDeVjKpQsa74Hj39+wEFV/DPQB8m1C
UyuIsdvrEiBqhiad71trzii9B4dg6lJELVfotV1XrCETtd+W21gpBA/z472lvXv1lnfUgS0gva4n
aJoaSsYUOmZvNCxpvhgs1M3BZymRon1L2DdkYpFQgaYH4W3ec/BYn+EG5WFdetAk36uxKxih19bl
4qBR5XBZNy6nAYHGWVNglvU5JCKyuP5uhSPDuImi324oSAq4EnAJ44BFFd4tt+bvK+Ev18Onh0dW
KaIomVnGq2IfZ9m91yxXsd5+w3hTOPlSkjuEeT5a2aMUzsDjwtNjspLPSqAgFcvFAFQ9Db6ORMkv
Z8sNWR68lSGQYNKCdCj+uLPI4Pm2CpfQIigxYx4LcCIgECwgk1NlkCrSzKi5ADgWHRO1zA/v1Nsn
X6AbzrFlh2txweXlvjxC4rZmsZNXfP9kvTzetKcHhKl4Lx+zKX3/Ga7jc5RRh1kuOXNLNxYi3LeH
dEDMHlJeyQ5gCFVvzWCDC/lF8cH3KGS2Fe8pnQVgYedJBFp09nRh96R0s8BW0A1E9HRxb8UBtQjo
vwRUTfQQo/qW3dva2t+9YCbnNDbjsFdd71ZGslb0wOrDsPvdfrJvmFmNWYo/9jl0wFE2SeE6KUvH
BP+vI533/Djrlw49JynbGzdUA8WwuTC5XVFeE1DkmOrmMa2boavqsqK8N9Wdl52bOW1hJhCYzJ4Y
fV3A9xRWheXiH9v9TtOKFoTRt7yQAMs6+dn0Rm66e5nrqLhjbA08b4oOOXbjIlQsGfctsKDNTk3Y
WiHEaSH970/cS/od+WCs0wRpGz5Q+PLzK2WMhSm+Rx3sdGND4DuJFnpVPfTuXjgGq4ouY4sLR8DD
WwOqGUwjIN6OhBSkMGQ0Dg+StNGVIswvuxVjooBoLaaV45xCCIarFvO00eJo9qG5QzGj31mAXyrb
V5yaMzcRGSSGjH9/+mlouzzy+cpV8Gqi2QjCaIGhTZkYZ1iDcXQW55dDTE/sBxYcD191cwotDD9H
U5o/kqjqZJ0ee6MX37XJQmEr1rJ8QRccx48zXPLas+f/28SZ9LqqY1F4fqX7H2rugekMWHoqKSck
EEIXQgJhRh/6vv315fNGNWWAsL291vok9v6sR6klewm1EMc27UamIyTwBi0t/0aLh1iHz+Y7Hnkz
rgcWwQ8eCDtPTHurk8FT/IJtl8o7lVGd1s7KHjSHjElfxP758PaYiScijlDuJ6KZy9AshwrBpwE7
BQW0YsoNbyTVMEB1RniItGCkuIHilR6NdBFEGkOxNtoUDyd52Wa9G4EcWrjQttR74M0n7qFgGzJT
YlTAqhcIbfJta/ZQAMsP1EKA7lBGC0YHXHkgLHW1bhBeO5agrII0KG5z48PzMqTwIcQC3CPvh6md
ND08wNQwmiziWd2qp7DpqoF9pnAzZg+OffH8QpEVSDSDX7j/KBNwgT/7FisJ2jYaO3n1V9JhpMHp
h77FmyORC3m9/f2TMrmPx/PplY4LKZmvnAiYV2JfxOJCN7CJ1kEge9NyXlqDCB+yFXJwFq04nRl3
gAEozXjpKT+vLMJZdwfXbAAG3Iyb6KXofKWHWFFSiIMZwqNCCjb2jY2WnEXN+tsKAUEqFq+ogXd4
nC64wiIk+xZ8febvHycWy5UCrgcj6Hqyp9rnFK5U4aLiDEPUoQKbjt1g6kcT5er14BRxoSDyI2tj
lEbMrQuxu2OgfN4qiMtwjiJwmhCjBbAbnKN8P94CIxif4Q6uIw0CGeBDqOu+vxJFvSekgq+lccz8
BqBvxs4CjlHajRX/9gNCeOekW8gbVvBlIeu31i6wm4fn2bXSaqFqsFILBEyg34giMBDqP0sO0Nh1
k+WH55FuOKJiB56oN03YOb7cfSTNs3mudWicOv8riPzzdJ6Qtp+lMMpVS2aGjnr4b6FwBDi7OmKL
VxyBKlCTpFHvjMFVbiP9TjkQ8h0L0fR91Vem3CHV9j5F3cPprh62cOMA0LmLGoaVICzdfPt8CVZY
Bf+QgAioXM8nCbyDnPGV+Md2fnsVJS2xXktlWxrv9pt8nRHSjGkUpekpUnlo+lx/O8WZf1zMtyGw
9Sm6x02zia/kenPCQ08N7r0khvb7B9ELlcfjMbH73Cl04ibTfjVZaXiU8r3vNsff2v0Yi5Z7JiRs
VoARcktb+eMcfzJgodMU9W1YcYUFXNX+7Sm+doMmjy8KoWdDCX37zE356bjUNbG7SCFnk9fNIVQ0
ISQeyJ5Cu0EEnzeNph/aSW7MuhT56u2o80hYJlD3dPvubf0t+7GN09S8GuG4lxylxW8Qi5p1aVox
6NU6S3PXBmbYlCd8tjL4Ll5nnQQimjKczu1bom/rpDcl152YM0drtudJlvQqYP3DzcPNv7085ZB6
wa6mxPd/5DQ2JUmzae29V5tBJaySUZF8EdMQ6Ym+/f2Toe7NpvqF+sgXhIwkDTqbDbJ+99kdOQ+m
jJZdfLwpzr1oCO+eLHjS0KlbEgum9ZRfc/vzZeImVk2BMOANHCZJJmPJh1a4ztj2C/W95FtkNh76
7IEEunvDNcpMTbPVmYu8yHULoq/nV96x3SNOwNxMgeKRzeQUWvi86AwjQpUjqa9+RSn7sXqxilDb
PkO11vPYLjsvLe04pKVnubEusiTDkI8qou5MyNyjkvKlveoP4jKZwLdvJeZTll9VFGYtOI1XY9jW
JVpSITMvtAxohH5uOA3ciQlJVnv7gUn0iVB2PyS0Vz+hsUb7EN9J9ZZ9eYVeHruLpEgc1E/PG5Qm
+Pp586ENd8qrHbR4ARs6jBvveA1L1p0mPu4/dH87w3MwZfmayeL5jUjufcxL4avUYURFELtV/32t
4yZI6DnDb6qOV+y37+/Bxngo5C0EJ90HWTSx2e0j4hfIRB5cJWfJLHEnd2GZXGZhlG+zf8kK7Rtz
gm4fiu/pi4sPhj3TgTUw4YrCKvQUxK5VelwvOhJpt4fV6yo0kZK4z1VV4/Tvn5ltWC/6Ri9WUItG
5Nca+8oaD28oh9e0sYbNgA+L5PClUWzb7/eaoHqgaEyDUZcwhMy85YC9k5e//YBpmD0pBzj0IpZp
GqTSLR5wTusxG5gvFrtcfVFwG9FsDRq8Jy924CtopU/OFxsJXoqYBdXR4IFqROKA1SRS6dIEEHrw
RG2UmCHoZafTP/DfYVb/jrU6jWNSh1WejP+B5Mk/8P+HZ/33f/dEi5FLSwAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formDESUSER = New-Object 'System.Windows.Forms.Form'
	$panel1 = New-Object 'System.Windows.Forms.Panel'
	$txtUsuario = New-Object 'System.Windows.Forms.TextBox'
	$labelUsuario = New-Object 'System.Windows.Forms.Label'
	$btnBuscar = New-Object 'System.Windows.Forms.Button'
	$statusstrip1 = New-Object 'System.Windows.Forms.StatusStrip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formDESUSER_Load = {
		#$txtUsuario.Focus()
	}
	$txtUsuario_KeyPress = [System.Windows.Forms.KeyPressEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.KeyPressEventArgs]
		#TODO: Place custom script here
		if ($_.KeyChar -eq 13)
		{
			$btnBuscar.PerformClick()
		}
	}
	$btnBuscar_Click={
		if ($txtUsuario.Text -eq '')
		{
			[System.Windows.Forms.MessageBox]::Show("Debe especificar un nombre de usuario.", '', 'OK', 'Exclamation')
			$txtUsuario.Focus()
		}
		else
		{
			$Usuario = $txtUsuario.Text
			$servidor = "DCOP01"
			try
			{
				$result = Invoke-Command -ComputerName $servidor -ScriptBlock {
					$Userinfo = Get-ADUser -Filter * -Properties LockedOut |
					Where-Object { $_.SAMAccountName -like "*$using:Usuario*" } |
					Select-Object -Property SamAccountName, DistinguishedName, LockedOut
					$lockstatus = $Userinfo.lockedout
					return $lockstatus
					
				}
				$Nombre = Invoke-Command -ComputerName $servidor -ScriptBlock {
					$Userinfo = Get-ADUser -Filter * -Properties LockedOut |
					Where-Object { $_.SAMAccountName -like "*$using:Usuario*" } |
					Select-Object -Property SamAccountName, DistinguishedName, LockedOut, Name
					$namestatus = $Userinfo.Name
					return $namestatus
					
				}
				if ($result)
				{
					$msg = "El usuario de ( $Nombre ) está bloqueado ¿Desea desbloquearlo?"
					if ([System.Windows.Forms.MessageBox]::Show($msg, '', 'YesNo', 'Question') -eq 'Yes')
					{
						try
						{
							$servidor = "DCOP01"
							Invoke-Command -ComputerName $servidor -ScriptBlock {
								Get-ADUser -Identity $using:Usuario -Properties LockedOut | Select-Object samaccountName, Lockedout | ft -AutoSize
								Get-ADUser -Identity $using:Usuario | Unlock-ADAccount
							}
							[System.Windows.Forms.MessageBox]::Show("El usuario de ( $Nombre ) a sido desbloqueado.", "", 'OK', 'Exclamation')
						}
						catch
						{
							[System.Windows.Forms.MessageBox]::Show("Error de ejecución: $($_.exception.message)", "", 'OK', 'Error')
						}
					}
					else
					{
					}
					
				}
				
				Else
				{
					
					[System.Windows.Forms.MessageBox]::Show("El usuario de ( $Nombre ) no está bloqueado", "", 'OK', 'Exclamation')
					
				}
			}
			catch
			{
				[System.Windows.Forms.MessageBox]::Show("Error de ejecución: $($_.exception.message)", "", 'OK', 'Error')
			}
			
	
			$txtUsuario.Text = ""
		}
			
	
					}
	#region Control Helper Functions
	function Update-ComboBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
		
		.PARAMETER ComboBox
			The ComboBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ComboBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
			
		.PARAMETER ValueMember
			Indicates the property to use for the value of the control.
		
		.PARAMETER Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red" -Append
			Update-ComboBox $combobox1 "White" -Append
			Update-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Update-ComboBox $combobox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ComboBox]
			$ComboBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]$DisplayMember,
			[Parameter(Mandatory = $false)]
			[string]$ValueMember,
			[switch]
			$Append
		)
		
		if (-not $Append)
		{
			$ComboBox.Items.Clear()
		}
		
		if ($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ComboBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$ComboBox.Items.Add($obj)
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)
		}
		
		$ComboBox.DisplayMember = $DisplayMember
		$ComboBox.ValueMember = $ValueMember
	}
	
	function Update-ListBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ListBox or CheckedListBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ListBox control.
		
		.PARAMETER ListBox
			The ListBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ListBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
			
		.PARAMETER ValueMember
			Indicates the property to use for the value of the control.
		
		.PARAMETER Append
			Adds the item(s) to the ListBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ListBox $ListBox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ListBox $listBox1 "Red" -Append
			Update-ListBox $listBox1 "White" -Append
			Update-ListBox $listBox1 "Blue" -Append
		
		.EXAMPLE
			Update-ListBox $listBox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ListBox]
			$ListBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]$DisplayMember,
			[Parameter(Mandatory = $false)]
			[string]$ValueMember,
			[switch]
			$Append
		)
		
		if (-not $Append)
		{
			$ListBox.Items.Clear()
		}
		
		if ($Items -is [System.Windows.Forms.ListBox+ObjectCollection] -or $Items -is [System.Collections.ICollection])
		{
			$ListBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ListBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$ListBox.Items.Add($obj)
			}
			$ListBox.EndUpdate()
		}
		else
		{
			$ListBox.Items.Add($Items)
		}
		
		$ListBox.DisplayMember = $DisplayMember
		$ListBox.ValueMember = $ValueMember
	}
	#endregion
	
	
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formDESUSER.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_txtUsuario = $txtUsuario.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$txtUsuario.remove_KeyPress($txtUsuario_KeyPress)
			$btnBuscar.remove_Click($btnBuscar_Click)
			$formDESUSER.remove_Load($formDESUSER_Load)
			$formDESUSER.remove_Load($Form_StateCorrection_Load)
			$formDESUSER.remove_Closing($Form_StoreValues_Closing)
			$formDESUSER.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formDESUSER.SuspendLayout()
	$panel1.SuspendLayout()
	$statusstrip1.SuspendLayout()
	#
	# formDESUSER
	#
	$formDESUSER.Controls.Add($panel1)
	$formDESUSER.Controls.Add($statusstrip1)
	$formDESUSER.AutoScaleDimensions = '6, 13'
	$formDESUSER.AutoScaleMode = 'Font'
	#region Binary Data
	$formDESUSER.BackgroundImage = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6AAAABGdBTUEAALGPC/xhBQAAAAlwSFlz
AAAOvQAADr0BR/uQrQAAIQpJREFUeF7tnVtwXdV5xzV5J3kDHkoewBNnCAOeZALlkkx8mcy04fIA
DjPYJjEzbQczuYBTbNNbAJcWjFBtSw6+0WKJFl/SwZYtc5FtyWTAkhMgtsG6DPKFSWRhQwOkTZt2
Znf9vn2WtM/W2keSdaTlE/7fzG/OOXuvvfY656z//tZ91T1R95lECBEPiVCIyEiEQkRGIhQiMhKh
EJGRCIWIjEQoRGQkQiEiIxEKERmJUIjISIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQ
iMhIhEJERiIUIjISoRCRkQiFiIxEKERkJEIhIiMRChEZiVCIyEiEQkRGIhQiMhKhEJGRCIWIjEQo
RGQkQiEiIxEKERmJUIjISIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQiMhIhEJERiIU
IjISoRCRkQiFiIxEKERkJEIhIiMRChEZiVCIyEiEQkRGIhQiMhKhEJGRCIWIjEQoRGQkQiEiIxEK
ERmJUIjISIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQiMhIhEJERiKsUeovujh4XNQe
EmFNUmevz9+zOGn+9h3J8wsWGJtvuTlZ88Wrkr9355+86KLcNeJCRSKsMf7BCezw1q3JqTfeTN55
8eWkb//+pLe9Penv7EzOnRxIsKH+3mTtddfLW9YIEmGNscqJcKDrcPJ37hVBZnnU0XznfBNi54ZN
LnzqMUNx4C25JnReTC8S4QVC6rVSYVQqShLuWVcELQqDwD4cHEzee+OXQZFxbH99fTLUc9y8aMOl
l7rjEmNMJMILgrpkzcyrkp9v354cbd2TbL3nO3bsqYv/KBcupUiACGpV3UXJWVcs/eDUgDtWLmjO
/ftf3Jf07ttn7zsaG5P//PjjZNfy5eZFVY+Mg0QYGYqFex59NPn9//y3FSO9bZl/uwnFh+O995Jr
ZswoO5eF42dPnUw+OD2QPD17jjXWeC/LuTWXX57Uf+5zTuDpMcJwb+qYhFM9cvqRCCOCAF/b0pIM
9fYkzQsWJZucYA47b4j9hytSpp6pzoSx7f7vOS+5O/nwV78y77Vz6bKgEFc7kSGqQVfcbLlrUdLd
0pz0dnYmx3bvtpZUiqvZ8MSxYc48u2f/wYOqJ0ZAIowEmZ1i4ZG2VhMCIDqKhUecYDCKiwcaGpLe
Vw8kv9i2Ldnpio2N116f9DlRvec8F2GJJxVO+rrWncdea2kZPoeIiQfb4Dwf93/qkkuG00I8eE9s
3bzZ8obTjEQYAYTxSv3jJgy8oT+OMKgHcgxv9rvf/tZ5s7stvG/NBK7DG+I1j+zdY10Vnes3WrG2
u7nZxLR9yX3D4RE4rakfvT+UbL715lF1P+6JcU91bUw/EmEU6pKfO8+2+ooryjxS9vzrLc+ZMBAN
nmr9nLnJ605gCGk8hoBPvflmcuTF3clzCxYmP3ZxnDjUVSZ6MFE3Ndo1506eHFVcFVOPRBgJio2M
bgmJEE9FsRMbOHTYPF6+4WaiRl2yz9X58Ije03GftS4NeFWsecHd5jXz6RFTi0QYCYTg64Kpdyr3
QIhloLvbxFFN69m/38SPB+S+73Z12XE8M5+LRKgi6tQhEUYCL7R+9hzzQni5ffWrTBgcBxpsxmNc
/95bv0x69u1L+trbk4MbNiUdrn5I0fXo7t3JYG9P8ruSp8va3pUrk2N703u854qtFHnpFmEIXEiI
jdfeYHVHibH6SIQRWH3xxa4Yellypud40vboo8lrpcYUvNE/ueLpUF+PfS4y6oWIdNePHrQ+Q98A
A6lHHQFxcc+t9yxOjrS2DRc9vQ319VmfIeLi+j2PPJJ0btho19L5zwOBaxF476uvJmvpZ5QQq4pE
OM3gTSyzO/G1r3rc3lMMbFmwyDxWXiRZG3zn7aRl4aJh4eGxxisIX+zl2vYnHx++D530NMbUf/aS
pME9AIj3k3NnLZy/lnor1267777kyJ497lgqbFEdJMJpBtE8fc1XrI+QjI0XAt63OS9UZPQZEqao
zjZeUtGmHrL/4H6LGw9H3BzfMv8OOxYan0qYdw91jzouJodEOMXgZcjwZGC8DOx/6qlkw5y5lpl9
UbDxqzck//e/vzcB5G3bkiV2XSj+88GPSSVdB+rr7R7UIRsuvSwZ7O+xeiHpzbfckoaBQ11J88K7
JcQqIhFOIWRa6nw0fNDSecwV5dpWrkw23XbzsCDJzLwyCiZku5Ytt/Oh+CeLL2a2Ll9h93p778vJ
tnvvtWPUW/PhEe1Qz9s2okdF0uohEU4ZdUnHurQTPGQfvz9kDTH/PPdbydqZXyodLTcabBBEOP7J
Qx3Q1wNJC8PjfEPOaOqSZ9zDA2O2x1Q9GD6NSIRTBJmZ4iWjVnj/N47VX7jS6nbUq8bqfGdQ91QK
EBqct6MFlOLw2lmzLL1rZl5p5zhGURqxNbjiK5OEvW345tdVHK0iEuEUQAZ9+hvpzITGq68ezrDZ
RhE+77j/B9aXF7Id96VjP7PxVhM8oJ/ORGMPaTp7eiDZufwhe7/GeeddK1bYshn+gUHXyXZXP9XQ
tuoiEU4BZNIDTz1lw8S84MKkE3fzDTIMMat83URIG4XsXqWGFvooeTCsnTEj6WrZYv2Hx9parWOf
2RR0hWQ9Nd0YNA4Rz2RbZ8VoJMIpAA92bHdbsuvBB8bItHVJZ9PaUlYfMepnnAtfM35IB/MVT7/1
VnKgqck+I3rS1Hjd9a5Y3JWsmzvbxAWDvb12fx4CHes3JVtK3RRcJ/FNHRLhFECm7W5pGdObEY5G
jrxx7eRFmM6OGOzvS86dTucKrp8zz7z007Pn2gTef3TvaX1lNAzi7Nyw2dVFe63+yvWEbV22QvW/
KUYinAIQ18ENG5P2J59wn0fExHH/Hs9CZg91TdCtMdl6Fw+Ad0ursuHlTnR32+x9pk+xwNMa97rr
wfvtfl0tzRaeaU/UC0kn9UVebcC3Cxu6h6gOEuEUwqJNHa646T8fdsVMX9eiHlg0RA1PNVnvg4CY
IYHQeY/IGmY6ATqvx8RdhElLLcto/K17v2flSrv3mf5ed/2ICNNhauF7iOogEU4jCAAxIAI67J9b
uCgoxIZLP29dB6E4xgstsTv+eoXV747udR7u1EmD9WSYysR8RUbtjBrQXeoaGRZha1swflE9JMJp
hM57X9eiOEo9jMHSWUMUCNC6EC65zAQz0aIpAsSbMrLlyEvtFieTg2mgOXP8uK3QzUwMBowPHX87
Geg+bC2jn5w9a2uS8qBAgE1XX23hQvcQ1UMinCYQXY/zhLuWPWTrxtBdgMDyc/3oi0OofhrRe2/+
0oa64Z1C8Rbh+ySbZs1yYtxjxVLiQGD+1RdT+ex55tZbksMtW6xVFQEysCBfryWcGmuqh0Q4TSCK
tc6z7PvxI8kBVxejgSQ0aJtV1Hymt2tmzLBJu3TqI5iJZH4Eg0ekbkgDzVjX8qBgcPZvXD0Rb8lS
iXTa+/MsoXjM1XNpTHr2zvkWnx8MLs4fiXCa8B4EIXkvhEDyxnqhWc8DhKf74DeufsdeE8STPZ8H
MSEQ+hu9Dfb1JT+Z9w27b6i+yTEWBmaANgtD+TTmw5E27t//6oEx0yHGh0Q4TQy+805yyhUtEcax
1jZbhoJiYt6ou+VFCAiCLgb6/XzHe1rkLA+H+FqciHr37x/ekwIB/ubXv7b4KdoSf36aEvVOJhoz
VQkBZs+Npi7pat5ScU8MMX4kwmmieeGi5Odbt9qQMFosi7onGOoW9kCphwO6Ok698ZZ5LisSOkF5
78Z56nGbbrpp2OvisYA9Lg6u35Q8O/8Om0lfHn+dLTB87KVXCu/v4TxpqEZ/ppAIp5U0c4+0jj79
jbm2PmjWKonQg6Do3jjl6orPzP1TC++FyDn69lhSMe+lfDGVdWzynpA4OjZuMs85VjGTsExMfre7
e8y0irGRCCPiZ1pkjREqY4kAvKAYCdOxrsmEnYquzjxuOtshFaEXKK2xxE+YbFw0rnDtrgeWWb0z
f55z/n7cB+9KVwZh03uOhBUTRyKcMtIiYD5DZ2kureeSNZaWGI93QTjUCblHp6sjnujqsjmBfKao
yKppXoSAWHbcuyTpaGo0IWXjAmuJdd7zQ1d3XPPFkRZR4mAjme333mcNNtsf+H7yenOLpfWjc2eD
9VIxMSTCKYBMziRYmvKZHU9jDOM16TzfdOvNw+G2Lv6OZeas9Y6jODoa6nuLrVth/ey5SeuKFdbo
w/GRYmedLa9BP2CRcEg33pCuCT4j3FAaMbwg4g8JWkwMibDKkClpZcTyfYDYYM87wx6Sibt5y9cJ
U29W3Mfn++m4hpn7NPzgCQcOldfXiIdia9bLhSA+hOc/c9+fzPpy8i/zvmWzMHg/0n0hAVYDibCK
IC4yJ6tbMxzNZ1bYfNu3SjJLZ0lsmD3PugvyxkraXjwIB89E5z7dDnTwewEXdU9wHo/LA4CFelOh
pI1BvIb6CEdw3rJ1j3nS/LnVM6+0Aek+baJ6SIRVg/l7a11GbbONOvPnEUfvzw6UpFZs3hP6lk7q
aN5oSaUfsXNdow3ERqSsipZfGQ3x+z0MmeHfsW5t0uFei7ypB6GyBmnDJaNHwbBkP3XAseIQE0ci
rAJkTFojabZHAFnvk60zrZ4xw5aRqGSIwERodTm8Wtqhz+yG3lc77D3G5FtEmnrE1NtyLz6THmZI
4Gmpu53oPmxF37EEhKel26PhkstGnWMXYaZhMfROjTHVRSKsEozxREA0whzeutWJbbd1FTCNqP3h
h4fDIZa0SJl6R8ZpZm1YhFZsTGfe4wEZ+4nAt5fqkXT2s1Q9cZxw3hGvt4udfGfNKgkyrUvynsYe
FvclbGg9UQ/FVwaQZ8eLAnHteOAHdt+mr2oT0WojEVYRMjmZHrGA/5wKYnR4jo8SYVnDTNrnRz2N
94T3C/V+7IqGFHsha9QFmVG/duZVFofvA6SYO1adjnPMOdx8W/luvnwX6pkUR9dUrFOK80EirDII
hYzPQkr5USl5LNOfPlGST2p+4i/nKV6++NgTyc6lyyxehLH1u9+1cIiXz0y+DbXC7rj33uH74LmI
kzVQKaIWPRQQ+qEtz5knJzzhmFXByBiMQduVRCzOD4mwqrji4g+/b/vII4LizO5J1/rMGiLEg/ow
vo7HexPhPYstHFtbcz0ipJ5Gwwktrp3rN9t5wo3cJxV867LlJjCuy57LQxcHxWDSQTEXY94jK3Cn
aUm7THz3iJgcEmGVIFOyj8OxvS+bF/HCqUTIE1IczYowC6L2fZB4Qjxl43U3JK8778U8RaZGcW/m
HzK2NHst6WHEDAKrJELuwf155QGAN183Z7allWPEw4JQdGOM5zuKsZEIqwSZnylD7GibtoimdUKO
p5k+lPHDIiwq8iEClijEUhFelGy+6abSDPgum/hLMfjI3labgJu9FsFsXfzdip6QMIjXVgB4cKnF
74/7MAiT4XasJMf6M9nWX3F+SIRVArHZDrpOCHTMs5IZ8wdpbTzy8j5bX2bdvDlJ0zXXWFig8STf
MENxtJJIfvpnSyyc94RNs2Yl77yYbpO9c/lya6WlMYdlNPLXNi+424RaFD8PDRpwqAdWqvshTta/
Oe2KqryGwojxIxFWjbrk2Ev7TCCTMTrjiwTgvRlG66g/jkeimEpxFIFQR8wOT0s9WZ0VR/2YUn8u
CyKkrslGoaHzWagPUvSWJ5w8EmEVoaiGGF58bJU1jJBRn194V7KvfpXzQHvMc5xwxUbqbKx81vdq
x6jdmZjPV8kT+gHVDIsLhcmDoJmR393cbOlbnesDLCdtKNp8y8gg8yKIh0HpRWkV40cirDJ4BkAw
vmXTN2psu/8HVgzF4/j6IrPss5Zd6CnPREVIOo62tZr4KSKnHjEcFkgnxdyxPCHfpcUVWVkmsVKx
VYwPiXAaINPSdcE8vKzAECmbhWYttNCTh3j8zAvEUiQqwvn3LDRMOBirSwFBnTt5Itnm7lF+Lh10
kAoufXgMuXQO9fdJhFVAIpwG8Hrpkvjp4r/Zc4xCydqZ3nQZ+mwYD+LyI2bOnhyweP05xMCaMzTQ
MJ2pyYkPkWevHwvi6N23zxp2SAPXb7rxRjvGQlVnXLzZbdOO7N0tEVYBiXAaQCyM/6RumG/IyIuw
kifkOLMiMDwWcSECPBytscy44Lz3fOE4KkNcdD/wSvwvLH1weEQOrxSfeQCwpVvoejFxJMIphozs
5w2ypkz+fF6Ep956yx0vFiEDsTGKoz92n9m8k8Hch7dvt12BJ+uZ8LZ+sDiekHGkdH3wHTbMnuPC
jBRLQ9eLiSMRTiFpHSxd6gJrWUAHus+8aUbOi5C6VrGQRvYztIHah7pMjCyZwTUTLX7mwXs+O//2
dI+Kvp6y+7AsPgPDmSJFOhDrZO8nUiTCKYaMjTfBPnl/yPapZ+7hi489aXWv/JKH/+UEEIoHiIsx
ol3OG1IcZc8IjmcbYiZHnW3lhiE++hR9ay4iR4ADTohtjzxigwHWXfNlCbEKSITTAJmYZezzfYJF
RrHSZ+58Jk8/p8LgNXtu8tRZfyKje5iriPAQOOKnWI0g6ep4rbnFuicYHVT9NHz6kAirjG/QQCTU
rZil3njtHycbXH3wp392n9WvKFIeaWu1Vkff6JE1361ABqd1Mi3Whu9XTUh3+6rHk/6D+03szLRn
CBv9hqSbYXnsq9jZ2Gj9lZwPxSMmhkRYRbyXYtQMY0AZ04nQju1us8+Myxzs7xnTI9Z/9mLrbviF
K66yLg3iCN2v2pjwZl45agBB1hjgzQMmfUiE4xETQyKsImuvucZWuKa7gKKb3xMwLbKl9So+s2zg
vy1YYJ3i1BPzxkK+rP35/D2LS9eH7zcVIETSzmrd7FXPeFTGq+51DxYeLhJf9ZEIJwmZFqFYxp35
JSuuPXPrzVZfGux524puvm5FWCbh+qIm11C3yhrD0cjwhK1eg8vE4f6Q1gdTpvuB8GlBIpwEZFIW
3P3o3JAVMemvyxY12ZjlQFOjbdLJhF8WYWKGwzNz/8QGeCNC9gPErK9v27bhbo3Q/cQfJhLhJGGh
JYppCOho624THXs3IDBfDGXlNBb8peWxq6U5Obh+Y/LC0uV2jqUEOefDI+zQfcQfLhJhFUgbTkZG
koTqTWnRckSYvqiZFvc4Vh5efHqQCIWIjEQopgTfqBMqFYhyal6EtNh5KA6mRUI/bjN8zVTg75fN
fFNRvyNO/z2zUKSd7u8cghW+SQ9r6bBG6pb5tw//JqHw54sv3ud/h1oUfU2LkD+X/dk/ODWQDPX1
2X4NLB/B4kPTmSERgH8QsFd8853zbR9Av40Yx6uROYhj8223WN8iA7c/ODlgsN8Eg6xD10wn/OYI
oWP9prJW4nOnTybr5s6pokCYTdJi35vpW/wWDDAANuWptTp2zYoQAa7+4lWlv3nE2CgzbfwIX1dN
fN9Z67KHbNMVuhmyRkZkqNfRtt22P/3kM2G6V3zI2MgFAYSvmy7qbC5iyAb7+6omQr4nD92Q7Vyx
ouQlw9deiNSsCPlD2bMvb6yrOR2ZkXswkiQ04iVkbBQz+XTVJUf3hnd16m5piS5CvD4PnSJruu6G
ihvSjBfG5BZZfh+NWqCGi6Ou2NPYWPrpR4w+t6kujpDZ6Q+ciO1YsmTST2gyeX6EjTcWBY7tASqJ
kClbDIWbbD2Z6zd/7WulWMuNuZn02072HtNNTYuw/+DB0s8/YnjH8T4JJ/pUTuuZdbZMxUSNmRST
zRyIv2jw97Pz75g2D1Bc33Z1tS3PlVJUbkxsDj0ciWsi9XfiYEZHyCiixi4NnA81K0Keuh+6CnnW
7Gl7xRVjZnYyK3+WJ+tBOJclGxfhWJNzokZdMbRSNfGTcdOMk8I9QuknLMtjhKxS/Nm48981j//O
efx5rs3Gl00nDzQ+87+83vLc8MOCtFE6Sa8ZuVd67Uhc2fOhNEB6vljob+99xeroPp5aoaZFmDf2
1uN4KLyHTLR+zjx7MrMhJ9ONWEaQ4yxLjyfFq9DCyaK5zCLwmY24aWAYy8iAWY/FCmVp5k3TQGbm
ic49WB2NRXT7f9Zh9dldy1fYhNpspkyvqRteaS1vFFGz35t7kWkZn0pdkRkZwDzGbfcuMc8T8ko8
YFoWLkpa7rrbfgfjrkUWF2nmWsbD0gh1qLnZ9r3gOMPybHcoVxTkGgaxb771ZpuLuPnWW6ybguX5
/X24N0XT9vrHbVtv0nagqcnSxb3Y64J4+P19OrYuTneZQmQD7v4ho9Eq/7vVAjUpQv4otunKG0vw
VXoScs6v95K3Yy5z7XxgWenTiL3y5BOWaXzmqGSImjA/mfWVZPONN9r2aBSZj+5uGxYhr2TKSmLG
e+xZuTL3XepsWYuQsQx+Nv4XfvSgdV0UGTM1/IPHx8/7fOsuRsPTevcgCtVFCc+EXy9Slu0IGQ+k
EU+dbh8Xuheb4/CALCpy86CBononi16RDv+daoWaFCEZ5pVVj5d++hHjaVr8JBxZJKnIzgQy2rq5
sy2TcT2DtIuM9WJIF2HxnECG4Biz6/32137ltfEY671wDR4CQbISW8i8ByCDdq7fWDo6tjGzg+tI
K/cIGf1wv/vkk9Kn0UaXUPqwqEv219eXjpYbDxwfxm+7XWT0+YWM0gTfjwdcSKSsULB21qzhUkst
UbMiZHehvFFsSQVTHh5Ptv2H3yuFmphRzAIyQH5DT2881amLhu7tsTSUVs+eiPmNOQEPFjKKbWTy
Aw0NpSPjMzIuS1SQNr/RzPkYDxvu39veXjpSbjy8+M+e+kL51t4TMf5v7lHkbfHYqdDDv/+FTE2K
0ATh6n95K3oKWhEml4HJgOzDR/9d0dPXL/OOCHkNFaEwRuqMlQE4X3R9JfM75lYqpiHQxmuvLzxf
yShR8PswyuV8jd+HNH5wevR/gr302BN2D9bVOV+jBGHpLBiswCpwEuE0gtjyGZqJtfxJ+eZuntJ+
/wZvCJCFl/jTEFe9y8ShOk+/q+N5EZLRz1eEeBq2qg4ZwmFj0KL+P44Tt98mO294R5bRKGoxpMUY
D1X0oOHedH6zFk7IWIOUui3LHxYZvzv9c0W/T/O359v5oocED0iGG1Z6iDDvkvvQiBUy1kWluBv6
/S90ak6EiMGv45k11mVBMPnwHKNFL2sdGza6c1nBurrao+k21FljMEAajvpdsScj87BMYbZRIK0T
pnVE0sDaMyHb9cByy1yECzU4UCfjvF/+Pm+0LCIi6mYhYx97E8kXriwdKbeh42+biBmHGTKWu+f6
XQV9c5+cPWvnm+ffXjoy2vgNi65H5KSN7/DCj0Y3jHnjv+J3ZAn+kLHjVS02ykDNiZCMHeqspeUw
9CQkg1CpzxpFOzK9D8OfF6pr4H045xtGPggUgb0NuXswLCt9ENRZkzwz7tsfftjSEMo81GMQqy9G
h1Y5Y5Ff81TOK4fs9ZYWS2Oovkgdlnv77xmydw8dTh5zYYqM1k++k19+P2+nSvsp0rUSMr4TIi8q
7vb/7MBwGilSh4zv4f/bogfhmpmTH40Ti5oTIRki1EpJkSn0JOQPzj/lEUtWhMSZH4ZGkdX3Efrp
ObSAVjI8IvVIljX0mYUHBpnwo/fft89ZIzxL2COy1hXhTMwyiXyHMwUDlreX+v1CIuQ78D2Jn5bj
kLHQL315IaOIn64tWmfFxZCxBwbpo48zZBR3K52n5ZT0EYZO/pDxAOIhyG8VMr4n12f/91qi5kTI
jx1qqqfzl8yCEFPS94TPezCKnogqW2TMFwWpQ2WFyvt182aXzo7fnp49x9Jwpud46Ui5IdazJ4s9
7LYffs/uXVRfYuEovmfRWqHEX1QfxBiFw7L2IWPrbNIORX1zFDMRCLM4Qsa6OpxnBfIiO+dKCYOl
vS9CxgOENBQVaQePH7d7ZPNJLVGTDTP5DEdGQ1h7V640eA+7/nKpie3I3vI6IRmahhKKpdTJ8sPf
sFNvvGl/fPa+/NHHJtDCR6MIcaSeNuyJKhlegmufdvW6kBE/ArR0vTi6y2Yso+EJL4Q3C9nR1jaL
m3sUGftTVHoIUKTn4Vg03nM8RtcO6aAlO2QMVpAIpwk8V9H4yZCRMRDB8wtHT3kay1gVzddDsuCV
ivoL88Y21WQO0s11RfWZkPGgYPMX0rDjrx4qHS03ttZGpMRNA0yRtwwZaeE6fp+iltlOV1Ql/n9d
sKB0pNx4CFBcpQO9yHz/acOln5/Q988a/znpLPK2vmST/69qhZoSIU/cfHdDJeMJz5/DH9j36oHS
0dEWmiBK0Yf75dNAhlo980tOAOEMkTX6+LyQiYtxmeMRCpmbDvg0Yzkvl2vd9cYCwyOZr7hemTce
Tt6DUZ8sEsdP/3yJxU8Lach89wlL44eMejDnaV0mfYilyCiNhIq8FKV5iJGOoiKxH9CQ/Z9qiRor
jtJK11L66ce2favScZ9cyx9JI0feKJIx1jJvDEAu+mM5TuZCqKGirLcXHnygTMikBe92+s03SyFG
2zFXtGIAt083mY+lKxBvFoxZ5NliGO8R+mBvuLuC66ijITzSxfdguQwaNvIgTFYu4P6+CJ6/P8e5
J407WPY8vNvdbdf7KWO8D3W1MPBi/Te/Pup6wNv774iRtux5S+fllw//BrVIzdUJERN/ynjIiojr
8IhNX73e5gMeaGy01k/CkSE5B76lbqwnKxkLoRC2YeYVyc6ly5KOjZts2XsGEnO9F1IWn36KaUzE
ZXwoYy6ZuUBcZFTCZK/x6crjPVk2rP8urPbNcvoMWG93DyNmSHDce2Z/HfcKxQ0+HaQ3nwZafNP4
itPnz5eT9s/uWrrclsLYcud8C8fvVSmOSukcfY/aoiYbZiZDKi7+uLGFNl7IIKnHS+NN34fDetJr
0vDjTQvC915lLLLxI+xqfddq4dN2oaUrBp86EQpxoSERChEZiVCIyEiEQkRGIhQiMhKhEJGRCIWI
jEQoRGQkQiEiIxEKERmJUIjISIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQiMhIhEJE
RiIUIjISoRCRkQiFiIxEKERkJEIhIiMRChEZiVCIyEiEQkRGIhQiMhKhEJGRCIWIjEQoRGQkQiEi
IxEKERmJUIjISIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQiMhIhEJERiIUIjISoRCR
kQiFiIxEKERkJEIhIiMRChEZiVCIyEiEQkRGIhQiMhKhEJGRCIWIjEQoRGQkQiEiIxEKERmJUIjI
SIRCREYiFCIyEqEQkZEIhYiMRChEZCRCISIjEQoRGYlQiKh8Jvl/N4Tk2WD9rkcAAAAASUVORK5C
YII=')
	#endregion
	$formDESUSER.BackgroundImageLayout = 'Stretch'
	$formDESUSER.ClientSize = '274, 231'
	$formDESUSER.FormBorderStyle = 'FixedSingle'
	#region Binary Data
	$formDESUSER.Icon = [System.Convert]::FromBase64String('
AAABAAIAICAAAAEAIACoEAAAJgAAABAQAAABACAAaAQAAM4QAAAoAAAAIAAAAEAAAAABACAAAAAA
AIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAN
AAAAFAAAABYAAAAWAAAAFgAAABQAAAANAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAIAAAAJAAAAGwAAADEAAAA/AAAAQwAAAEMAAABDAAAAPwAAADEAAAAbAAAACQAAAAIAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAACQAAACMaFhNIgnBdxJWAaf+Ufmj/k35o/5R+aP+Vf2n/gXBdxBoWE0gA
AAAiAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASZFdIc52Kcv/Ft6X/5+LW//Tw5P/z8OT/9PDk
/+fi1v/GuKf/nYpy/2BURnYAAAAjAAAAFgAAABYAAAAWAAAAFgAAABYAAAAWAAAAFgAAABYAAAAW
AAAAFgAAABYAAAAVAAAADQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABafinT/2M+9/97Vwf/T
xq7/zsGn/87Ap//Owaf/08au/97Vwf/b0cH/n4t1/wAAAEgAAABDAAAAQwAAAEMAAABDAAAAQwAA
AEMAAABDAAAAQwAAAEMAAABDAAAAQwAAAD8AAAArAAAADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
EqKOeP/JuqL/wK+U/76skf+9q5D/vauQ/72rkP++rJH/wK+U/8m6of+ijXf/lYBp/5WAaf+VgGn/
lYBp/5WAaf+VgGn/lYBp/5WAaf+VgGn/lYBp/5WAaf+VgGn/loJq/4l3YsQAAAAVAAAABAAAAA0A
AAAVAAAAFgAAABYAAAAep5N+/7Kegf+wm37/2s+2/+Tcy//k28r/5NzL/9rPtv+wm37/sZyA/6eT
ff/RxrL/0MWw/9DFsP/QxbD/z8Sv/8/Er//PxK//z8Sv/8/Er//PxK//z8Sv/8/Er//UybT/mINr
/wAAABYAAAANAAAAKwAAAD8AAABDAAAAQwAAAERMQzprqJWA+KmSd//Pwqr/vKmI/7ypiP+8qYj/
z8Kq/6mSd/+umoT/xrik/9LGsv/QxLH/0MSx/9DEsP/Pwq//zcCs/8y/q//Mv6v/zL+r/8y/q//M
v6v/zcCs/9PItv+WgWv/AAAAFgAAABWJd2LEl4Ns/5WBa/+VgWr/lIBq/5SAaf+Tf2n/kn5n/5mG
cf+RfGb/kX1m/5F8Zv+ZhnH/kn5n/5J+aP+RfWb/kXxl/5B7Zf+Qe2X/kHtk/6eWgP/Owq3/y7+q
/8u/qv/Lv6n/y7+q/8u/qv/Lv6r/1cu4/5eCav8AAAAWAAAAFpeDbv/Rup3/x6+P/8atjv/FrY7/
xa2O/8Stjv/ErI3/xKyN/8Ssjf/ErI3/xKyN/8Ssjf/ErI3/xKyN/8Ssjf/ErI3/xa2N/8aujv/N
tJb/kXxm/8/Drv/Kvqn/yr6o/8q9qP/Kvqj/yr6o/8y/qv/Yzr3/mINr/wAAABYAAAAWmIRt/9K9
of/Z0b3/7Ozn/+vs6f/q7On/6uvp/+nq6f/p6un/6Orp/+jp6f/o6un/6erp/+nq6f/p6+n/6uzp
/+vs6f/s7Of/2dK9/824m/+SfWb/zsKt///98f/Hu6X///vw/8i7pf///fL/y7+p/9rQwP+YhGz/
AAAAFgAAABaZhG7/1sKo/9LLuP/hjiT/45Ee/+mYIv/tnSL/86Qi//eqIv/8sCP//7Mj//2xI//4
qyL/9KUi/+6gIv/qmSL/5pMg/+GJGf/SzLn/0b2i/5J9Zf////b/yLml///57v/HuaP///nu/8m7
pv/Mv6r/3NPE/5mFbf8AAAAWAAAAFpmFcP/ayLL/zMSz/+OVMf/nnjr/6J0v/+yhLv/xqC//9a0v
//qzMP/+uDD/+7Uw//avL//yqS//7qQv/+meL//lmCz/4Y8j/8zFtf/Xw6r/kn1n/87BrP//+u7/
x7mk///57f/IuqX///vw/82/q//e1sf/moZt/wAAABYAAAAWnIdw/9/Puf/Hvqz/4pUy/+WgQf/q
pkT/7KU3//CmMP/zrDH/97Ax//qyM//3sTP/9K0y//GoMv/sozL/6J4y/+SYL//hjyX/x7+u/9rJ
sv+VgGj////1/8q8p///+e3/ybum///57v/Lvaj/zsCs/+HYyv+ahW7/AAAAFgAAABaciHL/5NXB
/8G3pP/hkTD/4549/+imRf/urE3/76xF//GpM//zqi//9Kww//OsMP/xqTH/7qUx/+uhMf/nnDD/
4pYu/+CNJP/Bt6b/39C6/5eBa//SxbD///zx/8y+qf//++//zL6p///88P/Pwq3/49zO/5uGb/8A
AAAWAAAAFp2Jc//o3Mn/vLGd/9+OLv/hmTz/5qFC/+qoSf/tr0//8LRV//G1U//xr0T/8Ks7/+yi
LP/roC3/55ss/+OXK//fkSn/34kh/7ywnP/k1sH/mINt/9XHtP/Rwq//0MKu/9DBrv/Qwq//0MGu
/9HCr//n3tL/nIdw/wAAABYAAAAWn4t1/+3i0P+3qZX/3Iws/9+XOv/jnUD/56NF/+qpS//srVH/
7rJX/++1Xf/vuGL/8Llo/++6bv/rtmr/67Zu/+u5eP/qtXP/tqeS/+ncyf+bhW//18q2/9XGs//U
xbH/1MWx/9TGsP/Uxq//0sWv/+jg1f+diHH/AAAAFgAAABagi3X/8unY/7Gjjv/ahin/3JI4/+CZ
P//jn0P/5qRI/+ioTf/qrFL/669X/+uxXf/rsmL/67Rm/+q0bP/ptXH/6LNz/+mvb/+woIj/7uHQ
/52GcP/dzLn/48q6/+PKuP/fy7T/4tCv/+DPrv/Yya//6+XY/56Icv8AAAAWAAAAFqGMd//47t//
rJyG/9aCJ//YjjX/3JQ9/+CaQf/in0b/5KNL/+amUP/nqVX/6Kxa/+itX//nrmP/569o/+awbf/m
r3H/5q1u/6uYgP/y6Nf/n4hz/+bMvv8Aij7/AIs9/+/Rtv8AGOf/ABfm/9/Orv/u5tr/n4lz/wAA
ABYAAAAWo453//v05/+nln7/030m/9aHMv/Zjzn/3ZQ+/9+ZRf/inUj/46FN/+SkU//lplj/5ahd
/+WpYv/krGb/5Ktr/+StcP/lrG7/ppJ4//fu3/+hinP/5s2//wDFUv8AxVH/7NC2/3lm//92Zf//
3s2u//Do3v+fiXP/AAAAFgAAABakjnn///ru/6KNc//TeSD/1H8p/9eGMP/cjTX/3ZE7/+GXQf/i
mkb/451M/+ShUf/ko1b/5KVb/+SmYf/kp2b/5Kls/+apbf+him///PXm/6GLdv/gzr7/5s3A/+bM
v//hzrr/4NG0/9/Qs//ZyrL/8Ovg/6CKdP8AAAAWAAAAFaaQev////X/mYBh/5uGaf+bh2z/moZs
/5qGa/+ahWv/moVq/5mEav+ZhGn/mYRp/5mDaP+Zg2j/mYNn/5mDZ/+ag2b/moJk/5l/X///+Oz/
o413/8Sri//Eqov/w6mK/8Kqiv/Cqoj/waiG/9jKtv/y7OT/oIt0/wAAABYAAAANqJN9////9///
//T////2////9v////b////2////9v////b////2////9v////b////2////9v////b////2////
9v////X////0///+8/+ijXf/waiH/7+nhv+/pob/v6aG/7+mhf++pYP/2Mq2//Tv6P+hjHX/AAAA
FgAAAASlkX2zp5J8/8/Crf/Nwav/zcCr/83Aq//NwKv/zcCr/83Aq//NwKv/zcCr/83Aq//NwKv/
zcCq/8zAqv/MwKr/zcCq/83Aq//Nwaz/pI54/8a5q////f3//fv6//z6+v/8+vr//Pr6//36+v/X
yLX/9vDq/6KNdv8AAAAWAAAAAAAAAASplYGwrZmD/6yXgv+sl4L/rJeC/6yXgv+sl4L/rJeC/6yX
gv+sl4L/rJeC/6yXgv+rloD/qJN9/6iTfv+qlID/qpaB/6qWgf+9q5j/3tG+/9vNuv/ZzLn/2cu4
/9nLuP/Zy7j/2cu4/9jJtv/39Oz/o453/wAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFqWQeP/8+fT/39G+/8Oriv/ErY3/xK2N/8SrjP/C
qor/waiJ/8Goif/BqIn/waiJ/8CoiP+/poX/2sy5//n18P+kj3j/AAAAFgAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWpI95//z48//bzLr/vqWE
/7+nhv+/p4b/v6eG/7+mhv+/pob/v6aG/7+mhv+/pob/v6aF/76kg//by7n/+/fy/6SPef8AAAAW
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABal
kHn/+/j0/9rKtv/7+vj/+/r4//v6+P/7+vj/+/r4//v6+P/7+vj/+/r4//v6+P/7+vj/+/r4/9rK
tv/7+PT/pZB5/wAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAFaaRe//8+vf/2sq2/9rJtf/aybX/2sm1/9rJtf/aybX/2sm1/9rJtf/aybX/
2sm1/9rJtf/aybX/2sq2//z69/+mkXv/AAAAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANqZR9/////f/9+vf//Pn1//z59f/8+fX//Pn1//z5
9f/8+fX//Pn1//z59f/8+fX//Pn1//z59f/9+vf////9/6mUff8AAAANAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASmkn6zqZN9/87Bq//MwKn/
zL+p/8y/qf/Mv6n/zL+p/8y/qf/Mv6n/zL+p/8y/qf/Mv6n/zMCp/87Bq/+pk33/ppJ+swAAAAQA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AASplYGwrZiD/6yXgv+sl4L/rJeC/6yXgv+sl4L/rJeC/6yXgv+sl4L/rJeC/6yXgv+sl4L/rZiD
/6mVgbAAAAAEAAAAAP4A///4AD//+AA///gAAAD4AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAD/
+AAA//gAAP/4AAD/+AAA//gAAP/4AAD//AABKAAAABAAAAAgAAAAAQAgAAAAAABABAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAzAAAAMwAAADMAAAAzAAAAGgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDcl6fmYVu/5iEbf+YhG3/mYRu/4FwXZoAAAAz
AAAAMwAAADMAAAAzAAAAMwAAADMAAAAjAAAAIwAAADMAAAAzpZJ8/7iihP/LvaX/y72l/7mkiP+l
knz/mINs/5iEbf+Xg2z/loFq/5WAaf+WgWr/i3lkwJB+acCbh3D/mYRt/5eCbP+WgGv/lH9p/5R/
af+WgGv/l4Js/5mEbv+ahm//sJ+J/9HHsv/QxLD/1cq3/5mEbP+einP/zbib//P58f/w9/H/7vbx
/+718f/u9fH/7vbx//D38f/z+fL/yraa/5mEbf/QxbD/zsKt/9fNuv+Yg23/nop2/9HDrf/kkCH/
65gg//SkIv/9sCP//7Mj//aoIv/tnCH/5Y4a/8+/qv+bhnH/1Maz/9HDr//b0cH/moVu/6CMeP/W
z77/45Qv/+ihN//vpS//9q0s//euLP/xpyv/6Zwp/+KOH//Vyrj/ooh1/+PKuv/gx7b/5dfJ/5yH
b/+ijnn/3trL/9+OK//moUD/7q5O//GxTf/xtlX/77Zc/+yzYf/stnL/3NTD/6yLev8AjkL/AIs+
//Ld0/+eh3L/o496/+Xl2P/YhCT/4Jc5/+akRf/qq0//7LBZ/+uyYv/ps2r/6K5r/+Lczf+tjHv/
AMlX/wDFU//14dn/oIlz/6WRfP/s7+P/0HUW/9mGKf/ekjX/45o+/+WgSP/lo1L/5KVc/+OkYf/n
5tb/p416/8mlkv/GoY7/8eXc/6GLdP+plH//8/fq//D27P/v9u7/7/bu/+717f/u9Oz/7vTr/+7z
6f/u8+f/7/Dj/6WOef/14tT/8d7Q/+/o3/+hi3b/rZmEsKuWgf+qlYD/qZWA/6mVgP+plID/qZSA
/6eSff+lj3n/pI54/6SPef+xnIb/uaGJ/7aehf/y7OP/o412/wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAClj3j/9/Lr/+7czP/u3M3/7t3N/+3czP/s2sr/9PDo/6WPeP8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAppB6//j07f/ay7f/2su4/9rLuP/ay7f/2sq3//jz7P+lkHr/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAKmUfv/++/X/+/by//v28v/79vL/+/by//v28v/++/X/qZR+
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACtmYOwqpV//6mTff+ok33/qJN9/6iTff+pk33/
qpV//62Zg7DgfwAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+
AAAA/gAAAP4AAAD+AAAA')
	#endregion
	$formDESUSER.Margin = '8, 7, 8, 7'
	$formDESUSER.MaximizeBox = $False
	$formDESUSER.Name = 'formDESUSER'
	$formDESUSER.StartPosition = 'CenterScreen'
	$formDESUSER.Text = 'DESUSER'
	$formDESUSER.add_Load($formDESUSER_Load)
	#
	# panel1
	#
	$panel1.Controls.Add($txtUsuario)
	$panel1.Controls.Add($labelUsuario)
	$panel1.Controls.Add($btnBuscar)
	$panel1.Anchor = 'Top, Left, Right'
	$panel1.Location = '0, -5'
	$panel1.Name = 'panel1'
	$panel1.Size = '275, 38'
	$panel1.TabIndex = 7
	#
	# txtUsuario
	#
	$txtUsuario.Location = '62, 10'
	$txtUsuario.Margin = '2, 2, 2, 2'
	$txtUsuario.Name = 'txtUsuario'
	$txtUsuario.Size = '136, 20'
	$txtUsuario.TabIndex = 1
	$txtUsuario.add_KeyPress($txtUsuario_KeyPress)
	#
	# labelUsuario
	#
	$labelUsuario.Font = 'Microsoft Sans Serif, 8.25pt, style=Bold'
	$labelUsuario.Location = '8, 8'
	$labelUsuario.Name = 'labelUsuario'
	$labelUsuario.Size = '53, 23'
	$labelUsuario.TabIndex = 11
	$labelUsuario.Text = 'Usuario:'
	$labelUsuario.TextAlign = 'MiddleCenter'
	$labelUsuario.UseCompatibleTextRendering = $True
	#
	# btnBuscar
	#
	#region Binary Data
	$btnBuscar.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlz
AAAOvAAADrwBlbxySQAAApZJREFUOE+NkWtIU3EYhw8V1IeCqD5E1EZgEiqJNWdZNtnIVpbmjWof
siDCD1YYFlHTlZJh5TZvHSejo+3WxsTaJcfm2Tojx7xMh7bphpuEF1iU1VDrQ/l2zjqUQWYPPJwX
fr/35Q8H+RscJnNdwWHWLQEv1SPgsgMCHlvKS929mY5XppibYslNS4T8A0m/Td/j53CQNXRleTLi
GTtL+CzQVRWDpDQPCg8mQw47EU6SsuMYCXRtefYnbN+kvnvh+zuiCSinbBIYUIngTOa+xVQmcytd
+zdWmRCfHXwGS624mN9Pxyvj6ZLnRAM4LLW5ojSbjldGV1S0en5qaGRhehgo5ya9LpFItIqO/49P
fvODhSkvzJN+HLUVPJfLN5hMJr7RaEyiK8vT3EnsmB3FI9FAN/n8bngfdHqDwcDbcDjcMz4+PhEK
hWrp6p/EXa5fm4+9rhQSM3NP/XOAj06CndQ9EgDb8MRXdzjiic5/qfP5fNMymYxBr/3k0D1tQnar
w3e81QmnsD44r/fDDfsMXMdnoMM5CBjxBuodY9DeG/rc0zcwjaJoMr2KIPGXRFs4ElOE22iFYzIC
crFeKFJ5QaDzx7zd2Q9m3AkY7gGF1QV6K7F4VqrfRa8jyN4q7dX0hy8gs94CWagDTshdkNc+AIXK
oZjUfEVJQJ3OApXKl8Bv6IISw5j5159JqdZeS6vthAyxGXiNNuC3EOSRHsh54o5JzfyWV7GM6rBq
9B94DdbFEkNAGDsgatKtv4lqys81dYSzpOZvXLKY9dgOR8klSmqmFvIajQtlqM5QLdOknxZryo80
2+/HDqjV6m1KpVJAWq5QKKrRNpXkUZtWUoNppZTiNo1E3q4Sk9kdslNGfgsxDNuIIAjyA5SnlMNk
sVtGAAAAAElFTkSuQmCC')
	#endregion
	$btnBuscar.ImageAlign = 'TopCenter'
	$btnBuscar.Location = '203, 10'
	$btnBuscar.Name = 'btnBuscar'
	$btnBuscar.Size = '67, 21'
	$btnBuscar.TabIndex = 2
	$btnBuscar.Text = 'Buscar'
	$btnBuscar.TextImageRelation = 'ImageBeforeText'
	$btnBuscar.UseCompatibleTextRendering = $True
	$btnBuscar.UseVisualStyleBackColor = $True
	$btnBuscar.add_Click($btnBuscar_Click)
	#
	# statusstrip1
	#
	$statusstrip1.Enabled = $False
	$statusstrip1.ImageScalingSize = '36, 36'
	$statusstrip1.Location = '0, 209'
	$statusstrip1.Name = 'statusstrip1'
	$statusstrip1.Size = '274, 22'
	$statusstrip1.TabIndex = 4
	$statusstrip1.Text = 'statusstrip1'
	$statusstrip1.ResumeLayout()
	$panel1.ResumeLayout()
	$formDESUSER.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formDESUSER.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formDESUSER.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formDESUSER.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formDESUSER.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formDESUSER.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
